# Generated by Django 4.2.3 on 2023-08-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_div_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='password',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='type',
            field=models.ForeignKey(default='Faculty', on_delete=django.db.models.deletion.CASCADE, to='app.type'),
        ),
    ]
