# Generated by Django 4.2.3 on 2023-08-29 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_director_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('No Action', 'C'), ('Accept', 'Accept'), ('Closed', 'Closed'), ('Escalated', 'Escalated')], default='STATUS_CHOICES', max_length=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.faculty')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
            options={
                'db_table': 'Complaint',
            },
        ),
    ]
