# Generated by Django 4.2.3 on 2023-08-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('No Action', 'No Action'), ('Accept', 'Accept'), ('Closed', 'Closed'), ('Escalated', 'Escalated')], default='No Action', max_length=10),
        ),
    ]
