# Generated by Django 4.2.3 on 2023-08-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_complaint_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='message',
            field=models.TextField(max_length=200),
        ),
    ]
