# Generated by Django 4.2.3 on 2023-09-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_student_department_alter_student_type_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='type',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='HOD',
        ),
    ]
