# Generated by Django 4.2.2 on 2023-09-14 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_hod_dept_remove_hod_type_delete_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='receiver',
            field=models.ForeignKey(db_column='receiver', on_delete=django.db.models.deletion.CASCADE, to='app.faculty'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='sender',
            field=models.ForeignKey(db_column='sender', on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user_type',
            field=models.ForeignKey(db_column='user_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.type'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department_name',
            field=models.ForeignKey(db_column='department_name', on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.CASCADE, to='app.type'),
        ),
        migrations.AlterField(
            model_name='student',
            name='type_data',
            field=models.ForeignKey(db_column='type_data', on_delete=django.db.models.deletion.CASCADE, to='app.type'),
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_Name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('dept', models.ForeignKey(db_column='dept', on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.CASCADE, to='app.type')),
            ],
            options={
                'db_table': 'HOD',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=55)),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.CASCADE, to='app.type')),
            ],
            options={
                'db_table': 'director',
            },
        ),
    ]
